### ISSUE TITLE
can libsurvive be used under 2nd lighthouse basestation?

### ISSUE THREAD

**Issue by chopin1998** [cntools/libsurvive#148] opened 2019-08-14 09:50 UTC
it show me 

`Warning: Could not find disambiguator state for WW0
Warning: Could not find disambiguator state for WW0
Warning: Could not find disambiguator state for WW0
Warning: Could not find disambiguator state for WW0
Warning: Could not find disambiguator state for WW0
Warning: Could not find disambiguator state for WW0
Warning: Could not find disambiguator state for WW0
Warning: Could not find disambiguator state for WW0
Warning: Could not find disambiguator state for WW0
Warning: Could not find disambiguator state for WW0
Warning: Could not find disambiguator state for WW0
Warning: Could not find disambiguator state for WW0
Warning: Could not find disambiguator state for WW0
Warning: Could not find disambiguator state for WW0
Warning: Could not find disambiguator state for WW0
Warning: Could not find disambiguator state for WW0
Warning: Could not find disambiguator state for WW0
Warning: Could not find disambiguator state for WW0
Warning: Could not find disambiguator state for WW0
Warning: Could not find disambiguator state for WW0
Warning: Could not find disambiguator state for WW0
Warning: Could not find disambiguator state for WW0
Warning: Could not find disambiguator state for WW0
Warning: Could not find disambiguator state for WW0
Warning: Could not find disambiguator state for WW0
Warning: Could not find disambiguator state for WW0
`

**Comment by jdavidberger** [comment] 2019-08-14 14:19
Should be fixed in latest master; please try again and see if the issue is fixed.

**Closed** 2020-03-04 17:01 UTC

**Comment by mossti** [comment] 2022-06-06 21:16
Hi! I wasn't sure if I should start a new issue or to reopen this one. I'm having the same problem as described by the original poster. I am on Ubuntu 20.04, and have two Gen 1 Vive lighthouses and 1 Gen 1 Vive controller connected via USB to my machine.

![image](https://user-images.githubusercontent.com/37938540/172250510-99fe37c7-0130-471e-a685-36a41a031669.png)

The above screenshot is what happens when I used the command `./bin/survive-cli`; I see the same behavior when including any combination of the following flags: `--force-calibrate --lighthousecount 2 --lighthouse-gen 0 --disambiguator StateBased`.  When trying to force calibration, I have been deleting the `config.json` file under the `~/.config/libsurvive/` directory; every time that the has file has been rebuilt the contents are as follows:

![image](https://user-images.githubusercontent.com/37938540/172250662-0c214315-b9e8-400b-87f6-bd22cedfe9b9.png)
